# Generated by Django 5.0 on 2023-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_hotel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_bookings',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='hotel_bookings',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotel_bookings',
            name='room_2b',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hotel_bookings',
            name='room_3b',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hotel_bookings',
            name='room_count_2b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel_bookings',
            name='room_count_3b',
            field=models.IntegerField(null=True),
        ),
    ]
