# Generated by Django 5.0 on 2024-01-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_remove_hotel_bookings_room_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_bookings',
            name='room_2b',
        ),
        migrations.RemoveField(
            model_name='hotel_bookings',
            name='room_3b',
        ),
    ]
